bert:
  name: 'facebook/bart-large-cnn'
  context_window:
  min_page: 1
  max_page: 1
  summarization:
    min_length:
    max_length:

pegasus:
  name: 'google/pegasus-xsum'
  context_window:
  min_page: 1
  max_page: 1
  summarization:
    min_length:
    max_length:

gemini:
  name: 'gemini-2.5-flash'
  min_page: 1
  max_page: 1000